"Fix" remaining undefined reference to klee_open_output_file
This code should actually not be used in Clover at the moment, thus
just disable the invocation of the undefined function via a CPP
guard.